# Generated by Django 4.0.2 on 2022-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_myuploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
