# Generated by Django 4.0.2 on 2022-04-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
