# Generated by Django 4.0.2 on 2022-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
