# Generated by Django 4.0.2 on 2022-05-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishToGujratiTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('gujarati', models.JSONField(blank=True)),
            ],
        ),
    ]
