# Generated by Django 4.0.2 on 2022-05-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_englishtogujratitranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnglishToGujratiTranslation',
            new_name='EnglishToGujaratiTranslation',
        ),
    ]
