# Generated by Django 4.0.2 on 2022-05-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0010_myuploadfilegujarati'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myuploadfilegujarati',
            new_name='myuploadgujaratifile',
        ),
    ]
